language: cpp

os:
  - linux

compiler:
  - gcc

env:
  - MPI=mpich2
  - MPI=openmpi

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

install:
  - sudo apt-get update -qq -y
  - sh test/travis-mpi.sh

before_script:
  - cd test

script: ./build_examples --noviz --clean
