language: cpp
dist: trusty
sudo: required

compiler:
  - gcc

env:
  - MPI=mpich2
  - MPI=openmpi

notifications:
  email: false

install:
  - sudo apt-get update -qq -y
  - sh test/travis-mpi.sh $MPI

before_script:
  - cd test
  - nproc

script:
  ./build_examples.sh -n 2 --noviz
