language: cpp

os:
  - linux

compiler:
  - gcc

env:
  - MPI=mpich2
  - MPI=openmpi

notifications:
  email: false

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

install:
  - sudo apt-get update -qq -y
  - sh test/travis-mpi.sh $MPI

before_script:
  - cd test

script: ./build_examples.sh --noexec --noviz && ./build_examples.sh --noviz --clean
